Update workflow to generate the lifecycle file automatically on PR.

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -7,10 +7,42 @@ on:
 
 jobs:
   lint:
+    permissions:
+      contents: write # Granting only the permission needed to commit and push
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - uses: hashicorp/setup-terraform@v3.0.0
-    - uses: actions/setup-python@v5.0.0
-    - uses: terraform-linters/setup-tflint@v4
-    - uses: pre-commit/action@v3.0.1
+      - uses: actions/checkout@v4
+      - name: Check if we need to generate files
+        run: |
+          make generate
+          git add .
+          # Check if there are any staged changes
+          if ! git diff --staged --exit-code; then
+            # If there are changes, check if the current branch is NOT 'main'
+            if [[ "${{ github.ref_name }}" != "main" ]]; then
+              echo "Generated files are out of date on branch '${{ github.ref_name }}'. Committing and pushing changes."
+              git config user.name "GITHUB ACTIONS AUTOMATED USER"
+              git config user.email "noreply@uw.co.uk"
+              git commit -m "[AUTOMATED]: generate files"
+              git push
+          
+              # Stop the job. The push will trigger a new workflow run.
+              echo "Stopping job because generated files were updated."
+              exit 1
+            else
+              # On the 'main' branch, fail the build instead of auto-committing
+              printf '%s\n' \
+                "----------------------------------------------------------------------" \
+                "FAILURE: Generated files on the 'main' branch are out of date." \
+                "HOW TO FIX: Run 'make generate' locally, commit the changes to a feature branch, and open a PR." \
+                "----------------------------------------------------------------------"
+              exit 1
+            fi
+          else
+            echo "Generated files are up to date."
+          fi
+
+      - uses: hashicorp/setup-terraform@v3.0.0
+      - uses: actions/setup-python@v5.0.0
+      - uses: terraform-linters/setup-tflint@v4
+      - uses: pre-commit/action@v3.0.1
